help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/cactus:2.9.9--py39h673081d_2

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
