help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/kraken2:2.1.3--pl5321h077b44d_4

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
