help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/blast:2.16.0--h66d330f_4

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
