help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/fastx_toolkit:0.0.13--0

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
