help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/eggnog-mapper:2.1.13--pyhdfd78af_2

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
