help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/mitobim:1.9.1--hdfd78af_1

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
