help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/stacks:2.65--h077b44d_1

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
