help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/iqtree:3.0.1--h503566f_0 

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
