help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/spades:4.0.0--haf24da9_4

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
