help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/velvet:1.2.10--h577a1d6_8

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
