help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/mafft:7.525--h031d066_1

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
