help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/vcftools:0.1.12b--pl5321h2e03b76_3

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
