help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/kraken:1.1.1--pl5321h9948957_10

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
