help:
    just --list

default:
    just build-env
    just build-sif

build-env:
    #!/bin/bash
    module load conda

    # Set a temporary environment name
    ENV_NAME="tmp_env_$(date +%s)"

    # Create the environment
    conda create -y -n $ENV_NAME bioconda::trimmomatic=0.39

    # Activate the environment
    source "$(conda info --base)/etc/profile.d/conda.sh"
    conda activate $ENV_NAME

    # Export the environment
    conda env export --name $ENV_NAME > environment.yml

    # Deactivate and remove the environment
    conda deactivate
    conda remove -y --name $ENV_NAME --all
    echo "Temporary environment $ENV_NAME created, exported to environment.yml, and deleted."

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
