help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/nextflow:24.10.3--hdfd78af_0

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
