help:
    just --list

default:
    just build-env
    just build-sif

build-env:
    bash build_env.sh

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def

reset:
    rm enviroment.yml final.sif
