help:
    just --list

default:
    just spack-to-docker
    just docker-to-raw

spack-to-docker:
    # This uses the spack.yaml to produce the Dockerfile
    spack containerize > Dockerfile

docker-to-raw:
    apptainer build raw.sif Dockerfile

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
