help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/flye:2.9.5--py39h475c85d_2

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
