help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/bowtie2:2.5.4--he96a11b_5

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
