help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/quast:5.3.0--py39pl5321h746d604_1

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
