help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/migrate-n:3.6.11--haf0c795_7

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
