help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/arcs:1.2.8--hdcf5f25_0

build-sif:
    apptainer build --force final.sif build.def
