help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/genrich:0.6.1--h577a1d6_5

build-sif:
    apptainer build --force final.sif build.def
