help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/minimap2:2.28--h577a1d6_4

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
