help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/gatk4:4.6.1.0--py310hdfd78af_0

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
