help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/bcftools:1.21--h3a4d415_1

build-sif:
    apptainer build --force final.sif build.def
