help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/ipyrad:0.9.103--pyh7e72e81_0

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
