help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/bowtie:1.3.1--py39h9046dc2_10

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
