help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/beast2:2.6.3--he65b2d3_2

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
