help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/deeptools:3.5.5--pyhdfd78af_0

build-sif:
    apptainer build --force final.sif build.def
