help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/megahit:1.2.9--h43eeafb_5

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
