help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/mothur:1.48.0--hb64bf22_1

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
