help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/prokka:1.14.6--pl5321hdfd78af_5

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
