help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/gblocks:0.91b--h9ee0642_2

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
