help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/trnascan-se:2.0.12--pl5321h7b50bb2_2

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
