help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/cutadapt:5.0--py39hbcbf7aa_0

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
