help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/bwa:0.7.18--h577a1d6_2

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
