help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/diamond:2.1.21--h13889ed_0

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
