help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/raxml-ng:1.2.2--h6747034_1

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
