help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/seqtk:1.4--h577a1d6_3

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
