help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/mauve:2.4.0.snapshot_2015_02_13--hdfd78af_4

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
