help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/sourmash:4.8.12--hdfd78af_0

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
