help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/sra-tools:3.1.1--h4304569_2

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
