help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/structure:2.3.4--h7b50bb2_7

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
