help:
    just --list

default:
    just pull-raw
    just patch-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/mira:3.4.1.1--1

patch-raw:
    #!/bin/bash
    echo "converting the raw sif to a sandbox to patch in changes"
    rm -rf sandbox_dir
    apptainer build --sandbox sandbox_dir raw.sif

    echo "Making scratch and storage directories"
    mkdir -p sandbox_dir/scratch
    mkdir -p sandbox_dir/storage

    echo "Rebuilding image"
    apptainer build --force raw_patched.sif sandbox_dir
    rm -rf sandbox_dir
    
build-sif:
    apptainer build --force final.sif build.def
