help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/bamutil:1.0.15--h5ca1c30_6

build-sif:
    apptainer build --force final.sif build.def
