help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/fastp:0.24.0--heae3180_1

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
