help:
    just --list

default:
    just pull-raw
    just build-sif

pull-raw:
    apptainer pull --force raw.sif https://depot.galaxyproject.org/singularity/hmmer:3.4--h503566f_3

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
