help:
    just --list

default:
    just build-env
    just build-sif

build-env:
    curl https://raw.githubusercontent.com/qiime2/distributions/refs/heads/dev/2024.10/amplicon/released/qiime2-amplicon-ubuntu-latest-conda.yml > environment.yml

build-sif:
    apptainer build --force --ignore-fakeroot-command final.sif build.def
